### ISSUE TITLE
Question about training data

### ISSUE THREAD

**Issue by huanghq-shanghaitech** [xdongming/GwentAI#1]
hello, i'm a student working on an AI project. I have a question that how do you solve the training data problem.
您好，我想请教一下您是如何解决训练数据这个问题的，谢谢！

**Comment by xdongming** [comment]
> hello, i'm a student working on an AI project. I have a question that how do you solve the training data problem. 您好，我想请教一下您是如何解决训练数据这个问题的，谢谢！

Hello,  there is a function 'cal_state' in the class 'Env'. When the agent take actions, the environment will return states and rewards, which will be used to train the network. I'm also an undergraduate in HUST, welcome to your discussion.
您好，环境类里有一个函数"cal_state"。当agent采取动作时，环境会返回状态和奖励，用于训练网络。我也是华中科技大学的一名本科生，欢迎交流！

**Comment by huanghq-shanghaitech** [comment]
Thanks. I still wondering how can you get the data set, or the DQN doesn't need data?
感谢回复！我可能表述存在问题，我想请教昆特牌的训练数据集怎么获取？谢谢！

**Comment by xdongming** [comment]
> Thanks. I still wondering how can you get the data set, or the DQN doesn't need data? 感谢回复！我可能表述存在问题，我想请教昆特牌的训练数据集怎么获取？谢谢！

There is no dataset, all data is collected from the environment.
没有训练数据集，所有的数据都是从环境中采集的。

**Comment by huanghq-shanghaitech** [comment]
I see. Does the environment means the real world( I notice that the opencv tech used in this project) or the environment created in  the code?
想继续请教一下这个环境是指现实中对局的采集还是指通过代码构建的虚拟对局？

**Comment by xdongming** [comment]
> I see. Does the environment means the real world( I notice that the opencv tech used in this project) or the environment created in the code? 想继续请教一下这个环境是指现实中对局的采集还是指通过代码构建的虚拟对局？

Here I use modeled reinforcement learning, so the environment refers to the environment created in the code.
这里我使用的是有模型强化学习，是从代码创建的环境中采集的。

**Comment by huanghq-shanghaitech** [comment]
OK, I think the problem is solved. Thank you for reply.
BTW, is the Gwent game the same as the one in the Witch3 game?
问题应该已经解决了，感谢回复。随便问一下，这个昆特牌是和巫师3中的昆特牌一样吗？

**Comment by xdongming** [comment]
> OK, I think the problem is solved. Thank you for reply. BTW, is the Gwent game the same as the one in the Witch3 game? 问题应该已经解决了，感谢回复。随便问一下，这个昆特牌是和巫师3中的昆特牌一样吗？

Yes, I only considered the Northern Realms' cards.
是的，我只考虑了北方领域的卡组。
